// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "Tree0":return img`
...............cc...............
............ccc65c66............
............c6c55c76............
...........6cc7557c66...........
..........cc77777577c6..........
.........666c677776cc66.........
........c7776c7c67657576........
........ccc666c666655666........
......c66cc7666667777c6766......
.....c777c77667667767767776.....
.....cc66cccc77c677cc666666.....
....c6766666c7c6767677777766....
...cc777666666677767777667c66...
.666cc6677666667777777776677666.
.67776677c676677777776677677776.
cc6666ccc67767776777776cc7767666
c666777667766776c776777c67776c66
.c6777666ccc667c676cc666667776c.
.cc6666766666cc66666666776cc666.
...66776c666666666677667766cccc.
...cc76c66766666667677667776c...
...6cccc677666666776777c77666...
......6ccc7c67767776c776cc......
........ccc6777c67776cc6........
...........cc77c67766...........
.............6c6666.............
............ffeeeef.............
..........ffeeeeeeeef...........
.............feeeffe............
..............fef...............
..............fef...............
...............f................
`;
            case "image5":
            case "Tree1":return img`
........................
..........cccc..........
..........c66c..........
.........cc66cc.........
........cc6666cc........
.......cc666666cc.......
......cc66666666cc......
......c66c6666c66c......
.....cc6c666c66c6cc.....
....cc6c6c6c6c6666cc....
...cc66cc66c66ccc66cc...
...ccccc66ccc66c6cccc...
....cc6c6cc6cc6c66c.....
....c66ccc66ccccc6cc....
...cc6cccc6ccccccccc....
...cccc66cccccc66cccc...
..ccc666cccc6ccc666cc...
..cc666cc6c66c6cc66ccc..
.cc6666666666c666666cc..
.c666c666666666666c66cc.
ccc6c666c66c6666c66c66cc
cc6c666c666c66c66c66ccc.
.ccc66cc66c66c6c66c666cc
.cc6cc66ccc66cc6c66cc66c
cc66cc6cc6c6c66ccc6ccccc
c66cc6cc66cccc66cccc6cc.
cccc66c66cccccc6c6cc66c.
.c6cccccccccccccc66cc6cc
ccc6cccccccc6cc6cc6c6ccc
cc66cc66c6cc66c666c6c6cc
c66c666c66c666c6c66c666c
ccc666c66cc6c66c6c66ccc.
.ccccc66cc666c6c66cccc..
.....c6cc66c66ccc6c.....
.....cccc6ccc6ccccc.....
........cccbbccc........
.........cbbbbc.........
........ccbbbbcc........
........cbbbcbbc........
........cbcbccbc........
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image7":
            case "Tree4":return img`
........................
..........cccc..........
..........c66c..........
.........cc66cc.........
........cc6666cc........
.......cccc666ccc.......
......cc6c6c6c66cc......
......c66c6cccc66cc.....
.....cc6c66c6c6c66c.....
....cc6c66c66c66cccc....
...cccccccc6ccccccccc...
....cccc6ccccccc6ccc....
.....c6cccc6cc6c66c.....
....c66ccc66cc6cc6cc....
...cc6cccc6ccccccccc....
...cccccccccccccccccc...
..ccccccccccccccccccc...
..cccccccccc6cccc6cccc..
.cc6ccccccc66c66cc6ccc..
cc66cc6cc6c6ccc66ccc6cc.
ccccc6ccc6ccc6cc6c6c66cc
.ccc6ccc66ccc66ccc6ccccc
..cccccc6ccccc66ccc6ccc.
.cc6cccccccccccccccccccc
cc66cc6cc6cc6ccc66cccccc
ccccc6cc66cc66ccc66ccc..
cccccccc6cccc6ccccccccc.
.c6cccccccccccccccccccc.
.cc6ccccccccccc6cccc6cc.
cc66cc66cccc6cc666cc66cc
c66cc66cccc66cc6c66cc66c
cccc66cc6ccc6c666c66cccc
.cccccc6cc6c6cc66cccccc.
.....cccc66cccccccc.....
.....cccccccccccccc.....
.........ccbbcc.........
.........cbbbbc.........
........ccbbbbcc........
........cbbbcbbc........
........cbcbccbc........
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "Pot":return img`
. . . . . c c c c c c . . . . . 
. . . . c d d d d d d c . . . . 
. . . c d b b b b b b d c . . . 
. . c d b c c c c c c b d c . . 
. . c d c c c c c c c c d c . . 
. c d b d c c c c c c d b d c . 
. c d d b d d d d d d b d d c . 
. c d d d b b b b b b d d d c . 
. c d d d d d d d d d d d d c . 
. c b d d d d d d d d d d b c . 
. c d b d d d d d d d d b d c . 
. c b d b b b b b b b b d b c . 
. c b b d d d d d d d d b b c . 
. . c b b b b b b b b b b c . . 
. . . c b b b b b b b b c . . . 
. . . . c c c c c c c c . . . . 
`;
            case "image9":
            case "TutorialGuyo":return img`
. . . . . . . . c c c c . . . . 
. . . . . . c c b b b b c . . . 
. . . . . c b b b b c c b c . . 
. . . . c b b b b b b c c . . . 
. c c c d b b b b b b d c c c . 
c b b b b d d d d d d b b b b c 
c c c b b b b b b b b b b c c c 
. . c c c c c c c c c c c c . . 
. . . c b b b b b b b b c . . . 
. . . c b c c b b c c b c . . . 
. . . . c b d d d d b c . . . . 
. . . c c c c c c c c c c . . . 
. . . c d c b b b b c d c . . . 
. . . c c c b b b b c c c . . . 
. . . . . c c c c c c . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "Tree2":return img`
........................
..........cccc..........
..........c66c..........
.........cc66cc.........
........cc6666cc........
.......ccc6666ccc.......
......cc666c6666cc......
......c66c6cc6c66c......
.....cccc6c6c66cccc.....
....cc66ccc66c66c6cc....
...cc66cc6c6c6ccc66cc...
....cccc66ccc66c6ccc....
.....c6c6cc6cc6c66c.....
....cc6ccc66ccccc6cc....
....c6cccc6ccccccccc....
...cccccccccccc66cccc...
...ccc6ccccccccc666cc...
..cc666cc6cc6cccc6cccc..
.cc666cc66cc6c66cc66cc..
cc666c6c6c6c66c666c66cc.
ccccc66cc66cc6cc666c66cc
.ccc66cc6cc6cc6ccc66cccc
..cc6cc66ccc6c66c6c6c6c.
.cc6cc66ccc66cc6c66cc66c
cc66cc6cc6c6c6cccc6ccccc
c66cc6cc66ccc66ccccc6cc.
cccccccc6ccccc6cc6cc66c.
.c6cccccccccccccc66cc6c.
.cc6cccccccc6ccccc6c6ccc
cc66cc66c6cc66cccccc66cc
c66c666c66c6c6c6ccc6c66c
ccc666c66cc6ccc66c666ccc
..ccccc6cc6cc66c6cccccc.
.....cccc66ccc6cccc.....
.....cccccccccccccc.....
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image3":
            case "SmallHeart":return img`
. c c . c c . 
c 7 7 c 7 7 c 
c 7 7 7 7 7 c 
c 6 7 7 7 6 c 
. c 6 7 6 c . 
. . c 6 c . . 
. . . c . . . 
`;
            case "image11":
            case "Enemyawaker":return img`
. . . . 2 2 2 2 . . . . 
. . 2 2 2 2 2 2 2 2 . . 
. 2 2 2 2 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 . 
2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 
2 2 2 2 2 2 2 2 2 2 2 2 
. 2 2 2 2 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 . 
. . 2 2 2 2 2 2 2 2 . . 
. . . . 2 2 2 2 . . . . 
`;
            case "image1":
            case "CatNpclol":return img`
. . . . . . . . . . . . . . . . 
. c c c . . . . c c c . . . . . 
. c d d c . . c d d c . . . . . 
. c b d d c c d d b c . . . . . 
. c b b d d b d b b c . . . . . 
. c d d d d d d d d c . . . . . 
. c d c d d d c d d c . . . . . 
. c c d c d c d c d c c c . . . 
. c d d d b d d d d c c d c . . 
. c c d b b b d d c c . c d c . 
. . c c c c c c c c c c c d c . 
. . . c d d d d d d b d d c . . 
. . . c d d d d b d d c c . . . 
. . . c d c c d c c d c . . . . 
. . . c c . c c . . c c . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "BatSleeping":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . c c c c c c . . . . . . . 
. . . c b d d d c . . . . . . . 
. . . . c b d c . . . . . . . . 
. . . . . c b c c c c c c c . . 
. . . . c c c b c b b b b b c . 
. c c c d d b c c d d d d d c . 
c d d d d b c b b c c d d c c . 
. c d d d b c b b b c d c c . . 
. . c c b c b b b b b c . . . . 
. . . c c b b b b b b c . . . . 
. . . c b c c c c c b c . . . . 
. . . c b b b b b b b c . . . . 
. . . . c c b b b c c . . . . . 
. . . . . . c c c . . . . . . . 
`;
            case "image12":
            case "BlueGem":return img`
c c c c c c c . . . . 
c d d d d d c c . . . 
c d c c c c d c c . . 
c d c d d 6 c d c c . 
c d c 6 c d d c d c c 
c d c c c 6 d 6 c d c 
c c d c 6 c c 6 c d c 
. c c d c c 6 6 c d c 
. . c c d c c c c d c 
. . . c c d d d d d c 
. . . . c c c c c c c 
`;
            case "image13":
            case "GreenGem":return img`
c c c c c c c . . . . 
c d d d d d c c . . . 
c d c c c c d c c . . 
c d c d d 7 c d c c . 
c d c 7 6 d d c d c c 
c d c 6 6 7 d 7 c d c 
c c d c 7 6 6 7 c d c 
. c c d c 6 7 7 c d c 
. . c c d c c c c d c 
. . . c c d d d d d c 
. . . . c c c c c c c 
`;
            case "image14":
            case "GreenGemFlash":return img`
c c c c c c c . . . . 
c b b b b b c c . . . 
c b c c c c b c c . . 
c b c b b b c b c c . 
c b c b b b b c b c c 
c b c b b b b b c b c 
c c b c b b b b c b c 
. c c b c b b b c b c 
. . c c b c c c c b c 
. . . c c b b b b b c 
. . . . c c c c c c c 
`;
            case "image15":
            case "SquareGem":return img`
. c c c c c c c c c c c . 
c c d d d d d d d d d c c 
c d c c c c c c c c c d c 
c d c 7 d d d d d 7 c d c 
c d c 6 7 7 7 7 7 d c d c 
c d c 6 7 7 7 7 7 d c d c 
c d c 6 7 7 7 7 7 d c d c 
c d c 6 7 7 7 7 7 d c d c 
c d c 6 7 7 7 7 7 d c d c 
c d c 7 6 6 6 6 6 7 c d c 
c d c c c c c c c c c d c 
c c d d d d d d d d d c c 
. c c c c c c c c c c c . 
`;
            case "image16":
            case "SquareGemFlash":return img`
. c c c c c c c c c c c . 
c c b b b b b b b b b c c 
c b c c c c c c c c c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c b b b b b b b c b c 
c b c c c c c c c c c b c 
c c b b b b b b b b b c c 
. c c c c c c c c c c c . 
`;
            case "image17":
            case "Health1":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
...ccccc.ccccc..................................
..cc677ccc677cc.................................
.cc67dd7c67dd7cc................................
.c6777dd7777dd7c.....ccccccc.........ccccccc....
.c67777d77777d7c....ccbbcbbcc.......ccbbcbbcc...
.c6777777777777c....cbccbccbc.......cbccbccbc...
.c6777777777777c....cbcccccbc.......cbcccccbc...
.cc67777777777cc....ccbcccbcc.......ccbcccbcc...
..cc677777777cc......ccbcbcc.........ccbcbcc....
...cc6777777cc........ccbcc...........ccbcc.....
....cc67777cc..........ccc.............ccc......
.....cc677cc....................................
......cc6cc.....................................
.......ccc......................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
`;
            case "image8":
            case "Health0":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
.....ccccccc.........ccccccc.........ccccccc....
....ccbbcbbcc.......ccbbcbbcc.......ccbbcbbcc...
....cbccbccbc.......cbccbccbc.......cbccbccbc...
....cbcccccbc.......cbcccccbc.......cbcccccbc...
....ccbcccbcc.......ccbcccbcc.......ccbcccbcc...
.....ccbcbcc.........ccbcbcc.........ccbcbcc....
......ccbcc...........ccbcc...........ccbcc.....
.......ccc.............ccc.............ccc......
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
`;
            case "image18":
            case "Health2":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
...ccccc.ccccc.....ccccc.ccccc..................
..cc677ccc677cc...cc677ccc677cc.................
.cc67dd7c67dd7cc.cc67dd7c67dd7cc................
.c6777dd7777dd7c.c6777dd7777dd7c.....ccccccc....
.c67777d77777d7c.c67777d77777d7c....ccbbcbbcc...
.c6777777777777c.c6777777777777c....cbccbccbc...
.c6777777777777c.c6777777777777c....cbcccccbc...
.cc67777777777cc.cc67777777777cc....ccbcccbcc...
..cc677777777cc...cc677777777cc......ccbcbcc....
...cc6777777cc.....cc6777777cc........ccbcc.....
....cc67777cc.......cc67777cc..........ccc......
.....cc677cc.........cc677cc....................
......cc6cc...........cc6cc.....................
.......ccc.............ccc......................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
`;
            case "image19":
            case "Health3":return img`
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
...ccccc.ccccc.....ccccc.ccccc.....ccccc.ccccc..
..cc677ccc677cc...cc677ccc677cc...cc677ccc677cc.
.cc67dd7c67dd7cc.cc67dd7c67dd7cc.cc67dd7c67dd7cc
.c6777dd7777dd7c.c6777dd7777dd7c.c6777dd7777dd7c
.c67777d77777d7c.c67777d77777d7c.c67777d77777d7c
.c6777777777777c.c6777777777777c.c6777777777777c
.c6777777777777c.c6777777777777c.c6777777777777c
.cc67777777777cc.cc67777777777cc.cc67777777777cc
..cc677777777cc...cc677777777cc...cc677777777cc.
...cc6777777cc.....cc6777777cc.....cc6777777cc..
....cc67777cc.......cc67777cc.......cc67777cc...
.....cc677cc.........cc677cc.........cc677cc....
......cc6cc...........cc6cc...........cc6cc.....
.......ccc.............ccc.............ccc......
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
................................................
`;
            case "image20":
            case "IntroBackground":return img`
................................................................................................................................................................
................................................................................................................................................................
.................c.................................................c.........................c..................................................................
..............................................................................................................c.................................................
..............................c.................................................................................................................................
................................................................................c.............................................c................c................
.....ccc....................................c............................................................cc.........................................c...........
.....ccc..........................ccc...................c.........c......ccc..........ccc...............ccc..........................ccc.................ccc....
.....ccc.......c..........c.......ccc....................................ccc..........cc................ccc........c.................ccc.................ccc....
..................................ccc....................................ccc..........ccc..........c.................................ccc.................ccc....
...................................................ccc..........................................................................................ccc.............
...................ccc.............................ccc......ccc.......ccc.................................................ccc.........c.........ccc.............
...................ccc.............................ccc......ccc.......c.c.........................cc.......................cc.c.................ccc.............
....................cc....ccc............c..................ccc.......ccc........................ccc.............ccc......ccc...................................
........c.................ccc...............ccc...................................c..............ccc.............c.c............................................
..........................ccc...............ccc............c.....................................................ccc.......................................c....
............................................ccc.........................................................c......c................................................
.............................c.........................................................................ccc....................c....................c............
....................................ccc...........ccc.....................ccc............ccc...........ccc............................c...c.....................
.........c..........................ccc...........ccc...........ccc.......ccc............ccc.......c...ccc................c.c............ccc.........ccc.c......
ccc.........ccc.........c...........ccc...........ccc..ccc......ccc.......ccc............ccc..c...........................cc........c....ccc.........ccc........
cc..........ccc........................................ccc....c.ccc.............ccc..........c............c.......ccc.....ccc............ccc..ccc....ccc........
ccc.........ccc..................................c.....ccc.............c........ccc........................cc.....ccc.c...ccc.................ccc...............
..................ccc.......................ccc.................................ccc....c.........................cccc.............c...........ccc...............
.....c............ccc......ccc........c.....ccc....c.....c.........................ccc..............c....ccc.......................c............................
........ccc.......ccc......ccc.........ccc..ccc..................c.......c.........ccc........ccc........ccc....................ccc...c...........ccc..ccc.....c
........ccc............c...ccc...c.....ccc...............c.c...................c...ccc........ccc........ccc...............c....ccc.....c..c......ccc.cccc......
........ccc.....c..............cccc....ccc.....c..c..........ccc.....................ccc......ccc.................ccc.c.........ccc.......c.......ccc.cccc......
........ccc.....................ccc...............ccc........ccc..................c..ccc..c................ccc....ccc.c..ccc...............ccc..................
...c..............ccc...ccc.....ccc..........c....ccc........ccc.....c..ccc..........ccc........c......c...ccc....ccc....ccc.......c.......ccc..................
..c...............ccc...ccc...c.................c.ccc....c.c............ccc......ccc.........c...cccc......ccc...........ccc....ccc........ccc...c....ccc....ccc
.c.......cccc.....ccc...ccc...........c...ccc..................ccc......ccc...cccccc.....c...c...ccc..cc.....c...........c......ccc...ccc..ccc........ccc....ccc
..........ccc...c...ccc................cccccc..................ccc....c.......cccccc..ccc..ccc...ccc......ccc.......c.....c.....cc....ccc..ccc.....c..ccc....ccc
......c...ccc.......ccc...c.......c...ccccccc...ccc...c.......cccc.........c..ccc.....ccc..cccc....ccc....ccc.........ccc....c........cc....ccc....ccc..........
...c................ccc......ccc...c.ccccc....c.ccc..cc..ccc......ccc................cccc..ccc.....ccc....ccc...c.....cccc..............c...ccc.c..cc....ccc....
..ccc..c......ccc............ccc.....ccc........ccc......ccc......cccc.............................ccc................ccc....cccc..cccc.....ccc.c..ccc...ccc....
..ccc..ccc....ccc...c.c......ccc.....ccc.............ccc.cccccc...ccc.....ccc..c...c.......c......c......c.........cc........ccc...ccccc...............c.ccc....
..ccc..ccc..c.ccc.c.....ccc.......c......ccc.....ccc.ccc..ccc............cccc.c....c......ccc.ccccc..ccc........ccc..........ccc...ccccc....ccc...c.............
.c.....cccc.......ccc...c.c.ccc........c.ccc.ccc.ccc.ccc..ccc....c....c...ccc....ccc..ccc.ccc.c.ccc..ccc.....cccccc.....ccc.......c..ccccc..ccc..ccc...ccc.c....
...ccc..ccc.......ccc.c.ccc.ccccccc......ccc.ccc.ccc.........c...c.......ccc.....ccc..ccccccccccccc..ccc.ccc.cccccc.....ccc..ccc.......ccc..ccc..ccc...ccc....c.
...cccc...........ccc....cccccc.ccc..ccc.....ccc......ccc.........ccc....ccc..c..ccc..ccc..ccc............cc.ccc...cccc.cccc.ccc...c...cccc......ccc...ccc......
..ccccc..c....ccccccc....ccc....ccc..ccc........c.....ccccc..ccc..ccc....ccc...............ccc....ccc....cccccc....ccc.......ccc.....cc...c.ccc.....c.ccc....ccc
..ccccc.......ccc.ccc....cccccc......ccc.c..ccc.......ccc.c..ccc..ccc..c.ccc.c....c.....c..ccccccccccc......cccc...ccc.........ccc..ccc..c..c.c..cccc.ccc.cccccc
..ccc.....ccc.ccc.ccccc..cc.cccccc..........ccc..ccccc..ccc..ccc.....c...cccccc.....ccc.......cccccccc.c....cccc.....ccccc.....ccc..ccc...cc.cc..cccccccc.cccccc
..ccc.....cccc......ccc.....cccccccc..ccccccccc..ccccc.c.....c....cccc......cccccccc.cc...ccc.cccccccc...ccc.ccc..c..ccccccc...ccc........ccc....cccccccc.ccc...
..c...cc..ccccccc.ccccc..c.....ccccc..ccc.ccc...cc.ccc....ccc.....ccc..ccc.c.cccccccccc...ccc.c..c.cccc.cccc.........ccccc....ccc.....c..ccccccc.c..ccccc.ccc...
.....ccc...ccccccccccc..cccc...c.ccc.cccc.ccc....cccccccc.ccc..cccccc..ccc.ccccccccc......ccc....cccccccccc.c.ccccc..cccc..c..ccccccccc..ccc.ccc.....ccc..cccc.c
.....ccc......ccccccccc..cccccc..ccc...cccccc....cccccccc.ccc..ccc.....cc..ccccccccc..ccc.............ccc.....ccccc..cccc.....ccccccccc..cc..cccccccc....c......
..c.cccc..ccc....ccccc...cccccc..cccc..cccccc.ccccc...ccc.ccccccccccccc....ccccccccc..cccccccc..ccccc...ccc..cccccc....c...cc...ccccccc....ccc..cccccc..cccccccc
c.cccccc..ccc.cccccccc....cccccccccccc.cccccc.cccccc......cccccc..ccccc.c..c.ccc.....cccccccccc.ccccc.c.ccc..ccccccccc...cccc...cccccccccccccc..cccccc..cccccccc
..cccccc.cccc.ccccccccccc.cccccc.cccc.......c.ccccc..ccccccccccc...cccccc..ccccccccc.ccc.ccccc..ccccc...ccc..ccccccccc....ccc...ccc.cccc.cccc.c.cccccc..cccccccc
...ccccc......ccc.....ccccccccccccccccccccccc.ccccc..ccccc......c.ccccccc..ccccccccc.ccc.ccccc..ccccc..............ccc....cccc..ccc....ccccccc..ccccc......ccccc
c..cccccccc.ccc.......cccccccc..ccccccccccccc.ccccc..ccccc..ccc...ccccccc..ccccccccc.....ccccc..ccccccc..ccc.c....c..ccc...cc........c.cccccccccccccc.cccccccccc
..ccc..cccccccc.....ccc..ccccc..ccccccccccccc......c.cccccc.ccc.....cccc...ccc..ccc.......ccc.c.....ccc..ccc...ccccc.ccc...ccc...cccc..cccccccccccccc.cccccc..c.
..ccc..cccccccccccc.ccc........ccc....ccc.....c...cccccccc..ccccccc.cccc..ccc...ccc..cccccccc.ccc.ccccc..ccc...ccccc.ccc..cccccccccccccc......ccccccc.cccccc..c.
ccccc..ccccc..ccccccccc.ccccccccccccccccccccccc...ccc..ccc.cccccccc.cccccccccc..ccccccccccccc.ccc.ccccc...ccc..ccccccc....ccccccccccccccc.c.cccccccc..c...c.....
ccccc..ccccccccccccccc..cccccccccccccc.cccccccccccccc..cccccccccccccc.cccccccc.ccccccccccc....ccc.ccccccccccc..ccccccc..c.cccccccccc.cccc...cccccccc..cccc..cccc
cccc...ccccccccccccccc..cccccccccccccc.cccccccccccc....cccccccccccccc.cccccccc.ccccccccccccc....ccccccccccccc..ccccccc...cccccc....cc.ccc...ccc.cccc.ccccc..cccc
ccccc....ccccccccccccc....cccccccccccc.cccccccccccc.....ccccccccccccc.cccccccc.ccc...ccccccc....cccccccccccccc.......ccc..cccccc...cccccccc....ccccc.ccccc..cccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`;
            case "image21":
            case "IntroLogo":return img`
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...666666...........666666.6666......66666...........66666..................66666.....................66666........
..6cccccc6.........6cccccc6cccc6....6ccccc6.........6ccccc6................6ccccc6...................6ccccc6.......
.6c66ddddc6.......6c66ddddc6dddc6666c66dddc666666666c66dddc6666666666.66666c66dddc66666666666..666666c66dddc66666..
6cc66ddddc6.......6c66ddddc6dddcccccc66dddc6ccccccccc66dddccccccccccc6cccccc66dddcccccccccccc66ccccccc66dddcccccc6.
6cc66ddddc6.......6c66ddddc6ddddddddc66dddcc66dddddddc6dddc66dddc6dddc66dddc66dddc66dddddd6ddcc66dddddc6dddc66dddc6
6cc66ddddc6.......6c66ddddc6dddddddddccccc666ddddddddc6dddc66dddc6dddc66dddcccccc66ddddddddddc66ddddddc6dddc66dddc6
6ccc66ddddc6666666c66ddddc66dddddddddc6dddc6dddddddddc6ddd66ddddc6dddc66dddc66dddc6ddddddddddc6dddddddc6ddd66ddddc6
.6cc66ddddc6ccccc6c66ddddc66dddc66dddc6dddc6ddddccccc66ddd66dddc66dddc66dddc66dddc6dddcc66dddc6ddddccc66ddd66dddc6.
.6cc66ddddcc66dddcc66ddddc66dddc66dddc6dddc6dddcccccc66ddd6ddddc66dddc66dddc66dddc6dddcc66dddc6dddcccc66ddd6ddddc6.
.6cc66ddddcc66dddcc66ddddc66dddc66dddc6dddc6ddddccccc66ddd6dddcc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66ddd6dddc6..
.6cc66ddddc66dddddc66ddddc66dddc66dddc6dddc6ddddddddc66dddddddcc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66dddddddc6..
.6ccc66dddd66ddddd66ddddcc66dddc66dddc6dddc66ddddddddc6ddddddccc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66ddddddc6...
..6cc66dddd6ddddddd6ddddcc66dddc66dddc6dddcc66dddddddc6ddd7dddcc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66ddd7dddc6..
..6cc66dddd6ddddddd6ddddcc66dddc66dddc6dddccccc66ddddc6ddd6dddcc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66ddd6dddc6..
..6cc66dddddddd7ddddddddcc66dddc66dddc6dddcccccc66dddc6ddd67dddc66dddc66dddc66dddc6dddcc66dddc6dddc6cc66ddd67dddc6.
..6ccc66ddddddd6dddddddccc66dddc66dddc6dddccccc66ddddc6ddd66dddc66dddc66dddc66dddc6ddddddddddc6ddddccc66ddd66dddc6.
..66cc66dddddd767ddddddccc66dddc66dddc6dddc6dddddddd7c6ddd667dddc6dddddddddc66dddc6ddddddddddc67ddddddc6ddd667dddc6
...6cc66ddddddc66ddddddccc66dddc66dddc6dddc6ddddddd7c66dddc66dddc67ddddddddc66dddc67dddddd7ddc667dddddc6dddc66dddc6
...6cc66777777c66777777ccc66777c66777c6777c67777777cc66777c66777c6677777dddc66dddc66777777677cc6677777c6777c66777c6
...6cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc66dddc66dddcccccccccccccccccccccccccccccccc6.
....6cccccccc6cccccccc666ccccc6ccccc6cccc6cccccccc66ccccc6ccccc6cccccc66dddc66dddccccccccccc66cccccccccccc6ccccc6..
...6666666666.66666666...66666.66666.6666.666666666.66666.666666c66ddddddd7c66dddc6666666666..666666666666.66666...
..6ccccc6.....6ccc6........................6ccc6ccc6..........6cc66dddddd7cc66dddc6................................
.6c6ddddc66666c6ddc666666..6666.666666.6666c6ddc6ddc66.66.66666cc66777777ccc66dddc6................................
6cc6ddddccccccc6ddc6ccccc66cccc6cccccc6ccccc6ddc6ddccc6cc6cccccccccccccccc66dddddc6................................
6ccc6ddcc6dddc6ddddc6ddddcc6dddc6ddd6dc6ddd6ddddccc6ddcddc6ddddccccccccccc66dddd7c6................................
.6cc6ddc6ddddd6dddd6dddddd6dddd6dddddd6dddd6dddd6dd6ddcdd6ddddddc6666666cc667777c6.................................
.6cc6ddc6ddcddc6ddc6ddccdd6ddcc6ddccdd6ddccc6ddc6dd6ddcdd6ddccddc6.....6cccccccc6..................................
.6cc6ddc6ddcddc6ddc6dddddd6ddcc6ddccdd6ddccc6ddc6ddc6dddc6ddddddc6......6cccccc6...................................
.6c6dddd6ddcddc6ddc6ddcccc6ddcc6dddddd6ddddc6ddc6ddc6dddc6ddcccc6........666666....................................
6cc6dddd6ddcddc6ddcc6ddddc6ddccc6ddd6dc6dddc6ddc6ddcc6dccc6ddddc6..................................................
6cccccccccccccccccccccccccccc6ccccccccccccccccccccccccc6ccccccc6...................................................
.6ccccccccccc6ccc66ccccc6ccc6.6cccccc6cccc6ccc6ccc66cc6.6ccccc6....................................................
..66666666666.666..66666.666...666666.6666.666.666..66...66666.....................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
...................................................................................................................
`;
            case "image22":
            case "IntroBird":return img`
............66666666........
..........66cccccccc66......
.........6cccbbbdddbcc6.....
........6ccbbbbddddddbc6....
.......6ccbbbbddddddddbc6...
.......6cbbbbbdddddddddc6...
......6ccbbbbbbddddddddbc6..
......6cbbbbbcccddddddccc6..
......6cbbdddcccddddddccc6..
.....6ccbbdddcccdddccdccc6..
.....6cdddddddddddcccccdc6..
.....6cddddddddddddddddddc6.
....6ccbbbbddddddddddddddc6.
....6cbbbbbbbbbbddddddddd7c6
...6ccbbbbbbbbbb77dddddd77c6
...6cbbbbbbbbbb77777777777c6
..6ccbbbbbbbbbb77777777777c6
..6cbbbbbbbbbb677777777777c6
.6ccbbbbbbbbbb777777777777c6
.6cbbbbbbbbbbc767777777777c6
.6cbbbbbbbbbb667676767676c6.
6ccbbbbbbbbbc666767676766c6.
6cbbbbbbbbbc666666676766c6..
6cbbbbbbbbc6c6666666666cc6..
6cbbbbbbbc6c6c6c666666cc6...
6ccbbbccccccccccc6c6ccc6....
.6cccccc66ccccccccccc66.....
..666666.6cc6666cc666.......
`;
            case "image23":
            case "IntroBird0":return img`
....................66666666.......
..................66cccccccc66.....
.............66..6cccbbbbddbcc6....
....66......6cc66ccbbbbbdddddbc6...
...6cc66...6cbbcccbbbbbdddddddbc6..
..6cbbcc66.6cbbbcbbbbbbddddddddc6..
..6cbbbbcc66cbbccbbbbbbbdddddddbc6.
..6cbbbbbbcccbbcbbbbbbcccdddddccc6.
..6cbbbbbbbbcccbddddddcccdddddccc6.
...6cbbbbbbbbbccddddddcccddccdccc6.
...6cbbbbbbbbbbbcccdddddddcccccdc6.
....6cbbbbbbbbbbbbccddddddddddddc6.
.....6cbbbbbbbbbbbbbccddddddddddc6.
......6cbbbbbbbbbbbbbddddddddd77c6.
.......6cbbbbbbbbbbb777dddddd777c6.
........6cbbbbbbbbbb777777777777c6.
.......6cbbbbbbbbbb777777777777c6..
......6cbbbbbbbbbbb777777777777c6..
.....6cbbbbbbbbbbb7777776767676c6..
....6cbbbbbbbbbbb6767676767676c6...
..66cbbbbbbbbbbb67676767666666c6...
.6ccbbbbbbbbbbb66666666666666c6....
6cbbbbbbbbbbbc66666c6c6c6c6ccc6....
6ccbbbbbbbbbc6c6c6c6c6c6c6ccc6.....
.6ccccbbbccccccc6c6c6cccccc66......
..666cccccccccccccccccccc66........
.....6666666cc666cc666666..........
............66...66................
`;
            case "image24":
            case "IntroBird1":return img`
....................66666666.......
..................66cccccccc66.....
.................6cccbbbbddbcc6....
................6ccbbbbbdddddbc6...
...............6ccbbbbbdddddddbc6..
...............6cbbbbbbddddddddc6..
..............6ccbbbbbbbdddddddbc6.
..............6cbbbbbbcccdddddccc6.
............66cbddddddcccdddddccc6.
.........666cccdddddddcccddccdccc6.
.......66cccbbbbbbbdddddddcccccdc6.
.....66ccbbbbbbbbbbbddddddddddddc6.
...66ccbbbbbbbbbbbbbcdddddddddddc6.
..6ccbbbbbbbbbbbbbbcbddddddddd77c6.
.6cbbbbbbbbbbbbbbbcb777dddddd777c6.
6cbbbbbbbbbbbbbbccbb777777777777c6.
6ccbbbbbbbbbbcccbbb777777777777c6..
.6cccccccccccbbbbbb777777777777c6..
..6666cbbbbbbbbbbb7777776767676c6..
....6cbbbbbbbbbbb6767676767676c6...
..66cbbbbbbbbbbb67676767666666c6...
.6ccbbbbbbbbbbb66666666666666c6....
6cbbbbbbbbbbbc66666c6c6c6c6ccc6....
6ccbbbbbbbbbc6c6c6c6c6c6c6ccc6.....
.6ccccbbbccccccc6c6c6cccccc66......
..666cccccccccccccccccccc66........
.....6666666cc666cc666666..........
............66...66................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "ZeldaDungeonMusic":return hex`005c000408070106001c00010a006400f401640000040000000000000000000000000000000002a00200000200012002000400012404000600012706000800012908000a0001200a000c0001240c000e0001270e001000012910001200012012001400012414001600012716001800012918001a0001201a001c0001241c001e0001271e002000012920002200012022002400012224002600012726002800012928002a0001202a002c0001222c002e0001272e003000012930003200012032003400012234003600012736003800012938003a0001203a003c0001223c003e0001273e004000012940004200011e42004400012244004600012746004800012948004a00011e4a004c0001224c004e0001274e005000012950005200011e52005400012254005600012756005800012958005a00011e5a005c0001225c005e0001275e006000012960006200011d62006400012064006600012766006800012968006a00011d6a006c0001206c006e0001276e007000012970007200011d72007400012074007600012776007800012978007a00011d7a007c0001207c007e0001277e008000012980008200011b82008400012084008600012586008800012788008a00011b8a008c0001208c008e0001258e009000012790009200011b92009400012094009600012596009800012798009a00011b9a009c0001209c009e0001259e00a0000127a000a2000119a200a400011ea400a6000125a600a8000127a800aa000119aa00ac00011eac00ae000125ae00b0000127b000b2000119b200b400011eb400b6000125b600b8000127b800ba000119ba00bc00011ebc00be000125be00c0000127c000c2000119c200c400011ec400c6000122c600c8000125c800ca00011eca00cc000122cc00ce000125ce00d0000129d000d2000122d200d4000125d400d6000129d600d8000125d800da000129da00dc00012adc00de000129de00e0000125`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
